"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](pink)\
$os\
$username\
[](bg:purple fg:pink)\
$directory\
[](fg:purple bg:green)\
$git_branch\
$git_status\
[](fg:green bg:yellow)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$dotnet\
[](fg:yellow bg:orange)\
$docker_context\
[](fg:orange bg:current_line)\
$time\
[ ](fg:current_line)\
$line_break$character"""

palette = 'dracula'

[palettes.dracula]
background = '#282a36'
current_line = '#44475a'
foreground_origin = '#f8f8f2'
foreground = '#4f0736'
comment = '#6272a4'
cyan = '#8be9fd'
green = '#50fa7b'
orange = '#ffb86c'
pink = '#ff79c6'
purple = '#bd93f9'
red = '#ff5555'
yellow = '#f1fa8c'

[os]
disabled = false
style = "bg:pink fg:foreground"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:pink fg:foreground"
style_root = "bg:pink fg:foreground"
format = '[ $user ]($style)'

[directory]
style = "fg:foreground bg:purple"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:green"
format = '[[ $symbol $branch ](fg:foreground bg:green)]($style)'

[git_status]
style = "bg:green"
format = '[[($all_status$ahead_behind )](fg:foreground bg:green)]($style)'

[nodejs]
symbol = ""
style = "bg:yellow"
format = '[[ $symbol( $version) ](fg:foreground bg:yellow)]($style)'

[c]
symbol = " "
style = "bg:yellow"
format = '[[ $symbol( $version) ](fg:foreground bg:yellow)]($style)'

[rust]
symbol = ""
style = "bg:yellow"
format = '[[ $symbol( $version) ](fg:foreground bg:yellow)]($style)'

[golang]
symbol = ""
style = "bg:yellow"
format = '[[ $symbol( $version) ](fg:foreground bg:yellow)]($style)'

[php]
symbol = ""
style = "bg:yellow"
format = '[[ $symbol( $version) ](fg:foreground bg:yellow)]($style)'

[java]
symbol = " "
style = "bg:yellow"
format = '[[ $symbol( $version) ](fg:foreground bg:yellow)]($style)'

[kotlin]
symbol = ""
style = "bg:yellow"
format = '[[ $symbol( $version) ](fg:foreground bg:yellow)]($style)'

[haskell]
symbol = ""
style = "bg:yellow"
format = '[[ $symbol( $version) ](fg:foreground bg:yellow)]($style)'

[python]
symbol = ""
style = "bg:yellow"
format = '[[ $symbol( $version) ](fg:foreground bg:yellow)]($style)'

[dotnet]
symbol = "󰌛"
style = "bg:yellow"
format = '[[ $symbol( $version) ](fg:foreground bg:yellow)]($style)'

[docker_context]
symbol = ""
style = "bg:orange"
format = '[[ $symbol( $context) ](fg:green bg:orange)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:current_line"
format = '[[  $time ](fg:foreground_origin bg:current_line)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:cyan)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:cyan)'
vimcmd_replace_one_symbol = '[](bold fg:cyan)'
vimcmd_replace_symbol = '[](bold fg:cyan)'
vimcmd_visual_symbol = '[](bold fg:purple)'